### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by lachlanhickey** [jobsta/reportbro-lib#11]
I note that the reportbro.com demo server reports back with errors, my server of reportbro-lib just gives me a 500 error if there is any mismatch or issue. 

Any advice of where we might be able to enable error reporting?

**Comment by alhman** [comment]
I assume by error reporting you want to see errors for preview in the Designer?
Basically there are 2 places where you have to catch pontential errors. First when the report object is created:
```
report = Report(report_definition, data, is_test_data)
if report.errors:
    return json.dumps(dict(errors=report.errors))
```
and second when the pdf is generated (in this case an exception is thrown to stop pdf generation):
```
try:
    report_file = report.generate_pdf()
except ReportBroError as err:
    return json.dumps(dict(errors=[err.error]))
```
In both cases you need to return json data containing the errors as a list.

You can also have a look at the demo application [here](https://www.reportbro.com/docs/setup)

**Comment by lachlanhickey** [comment]
Hmm, so the reportbro_server.py doesn't return the 'preview' errors that the reportbro.com server generates?

The same preview on your server returns 
`{"errors": [{"info": "Split_Swim380m", "field": "content", "msg_key": "errorMsgInvalidExpressionNameNotDefined",
"context": null, "object_id": 4053}]}`

Where my server just returns `500: Internal Server Error`.

Is there something I need to turn on to get my django to return errors/json?

**Comment by alhman** [comment]
You're right, there is currently a bug in the reportbro_server.py script. We'll update this soon. You can fix it yourself in the meantime by replacing
```
if report.errors:
    return json.dumps(dict(errors=report.errors))
```
with
```
if report.errors:
    self.write(json.dumps(dict(errors=report.errors)))
    return
```

So you already have an existing Django application? If that's the case I don't understand why you use the reportro_server.py script, it's probably a better option to directly integrate reportbro into your existing app.

**Comment by lachlanhickey** [comment]
I'm not actually running my primary app in Django, I have just set up a container for the reportbro-lib server :)

Thanks for all your help

**Comment by lachlanhickey** [comment]
No luck with that code swap, unfortunately. :(

`500 Error`

with

`HTTPServerRequest(protocol='http', host='localhost:8000', method='PUT', uri='/report/run', version='HTTP/1.1', remote_ip='172.17.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
TypeError: object str can't be used in 'await' expression
ERROR:tornado.access:500 PUT /report/run (172.17.0.1) 8.99ms`

**Comment by alhman** [comment]
there are 2 places in the script with
```
return json.dumps(dict(errors=report.errors))
```
make sure both of them are replaced with
```
self.write(json.dumps(dict(errors=report.errors)))
return
```
and of course don't forget to restart your server.

**Comment by lachlanhickey** [comment]
👍

**Comment by lachlanhickey** [comment]
I must be missing something. 

I now get a response 

`{"errors": []}`

Expecting

`{"errors": [{"info": "Personal.Fullnames", "field": "content", "msg_key": "errorMsgInvalidExpressionNameNotDefined", "context": null, "object_id": 4059}]}` 

As generated on reportbro.com

**Comment by alhman** [comment]
sorry, there's another issue. We'll test this script in the next days and upload a fixed version.
For now you can replace
```
except ReportBroError:
    self.write(json.dumps(dict(errors=report.errors)))
    return
```
with this
```
except ReportBroError as err:
    self.write(json.dumps(dict(errors=[err.error])))
```

**Comment by alhman** [comment]
The reportbro_server.py script is fixed and updated. Can I close this issue?
