### ISSUE TITLE
Can't add an image dynamically

### ISSUE THREAD

**Issue by ericmartin33** [jobsta/reportbro-lib#15]
Hello

I try to insert an image in a report.
Steps :
in designer : 
1) add parameter, select image and name logo
2) add an image widget on the report
3) set ${logo} in data source of the widget.

I'm using django and i don't know the way to pass the logo image in this line :

`params = dict(logo=my_logo)`

I tried : 
- base64 image:     

```
with open(file_db.file.path, "rb") as img_file:
        my_logo = base64.b64encode(img_file.read())
```

- full path :
my_logo = file_db.file.path

- path to static :
my_logo = /media/myimage.png

- exposed url by server :
my_logo = 'http://localhost:8000/media/myimage.PNG'

i keep this error:
report error: {'msg_key': 'errorMsgInvalidImage', 'object_id': 11, 'field': 'source', 'info': None, 'context': None}

**Comment by alhman** [comment]
If you're encoding the image with base64 then the format has to be
`"data:image/<image type>;base64,<encoded image data>"`

but in your case it would be much easier to just pass the file object as parameter:
`my_logo = open(file_db.file.path, "rb")`

**Comment by ericmartin33** [comment]
Thanks ! it works.

But i had to add the prefix with this code :

```
    ext = file_db.file.path.split('.')[-1]
    prefix = f'data:image/{ext};base64,'
    with open(file_db.file.path, "rb") as img_file:
        my_string = base64.b64encode(img_file.read()).decode()
```

**Comment by alhman** [comment]
great. As I mentioned it would be easier if you just pass the file object:
```
my_logo = open(file_db.file.path, "rb")
params = dict(logo=my_logo)
```
There is no need to convert it to a string if the image file is already available.

**Comment by ericmartin33** [comment]
Nope, didn't work.

Seems to be a python 2/3 change and my image stored in a filefield with django:
https://stackoverflow.com/questions/6375942/how-do-you-base-64-encode-a-png-image-for-use-in-a-data-uri-in-a-css-file/49475135

Thanks for your answer, and for your project. Really awesome!

**Comment by alhman** [comment]
hmm, that's strange. You could debug and find out why it does not work:
https://github.com/jobsta/reportbro-lib/blob/71ef5b95100b04c6636f24b5e287d24670694919/reportbro/reportbro.py#L309

The parameter should be an instance of BufferedReader or file (in Python 2). Let us know if it's something we can improve in the lib.

Anyway, I'm glad you found a working solution.

**Comment by ericmartin33** [comment]
Found !

your supported type list is ('png', 'jpg', 'jpeg')
My image is : xxx.PNG

Can you change to case insensitive ?

**Comment by alhman** [comment]
done: 3b66be388023d3f8c6089b7ecfb74f9357906e36
