### ISSUE TITLE
"Page break" is not working in PDF

### ISSUE THREAD

**Issue by qmainuddin** [jobsta/reportbro-lib#20]
I have added **page break** between two sections on my designer page. Then I tried to export PDF by calling **generate_pdf** method. Which returns a PDF with no page break ! 

My expection: Showing two sections in different pages
Result Found: Showing sections one after another on same page

**Comment by alhman** [comment]
Are you sure the page break is inside the content area of the document and not inside the content area of the section (check the element structure on the left side)? In case of the latter the page break has no effect - which is probably also a bug, we'll have a look into this.

Can you post your report so we can easily reproduce this? Look [here](https://www.reportbro.com/guide/view/6/debug-mode) how to export a report.

**Comment by alhman** [comment]
Page break now also works inside section content.
