### ISSUE TITLE
May you use fpdf2 because its faster

### ISSUE THREAD

**Issue by alisufyanbaig-dev** [jobsta/reportbro-lib#24]
Hi, I am using reportbro for a long time, I came across a library fpdf2 it's way faster because generating around 5k pages takes 100 seconds on report bro on my i5 machine windows 10 py 3.9.

**Comment by alhman** [comment]
we are now using fpdf2 internally for pdf generation

**Comment by alisufyanbaig-dev** [comment]
Thank you so much you guys are awesome
