### ISSUE TITLE
Table component with mutli groups expression

### ISSUE THREAD

**Issue by mterceno** [jobsta/reportbro-lib#26]
Hello,

I have a rather strange behaviour when I print this type of report.

The report is simply composed of a Table which is linked to the structured data in the following way:
Family, Type, Group, Quantity

I have calculated myself (in this data) the sums of 4 groups I want to display.

In this report, I want to have a break :
- for sum_ftg_group => sum
- for sum_ft_group => sum
- for sum_f_group => sum + page break
- for sum_group => sum total

Everything works fine except the page break on sum_f_group (3rd). On the next page, the first break is not on sum_ftg_group.

In the attached PDF file, you will notice on page 2 that the break (sum_ftg_group) 1A0 does not occur. Same thing on the 3rd page with 2A0

Have I done something wrong?

![image](https://user-images.githubusercontent.com/4966754/215513633-1cb0b632-cfd3-4ca9-92bf-ac16b93d08ff.png)

[deabadd5-f567-4628-b1dd-91fc9ddb9059.pdf](https://github.com/jobsta/reportbro-lib/files/10536920/deabadd5-f567-4628-b1dd-91fc9ddb9059.pdf)
[reportbro_example.txt](https://github.com/jobsta/reportbro-lib/files/10536921/reportbro_example.txt)

ReportBro version is 3.0 / 3.0.5

**Comment by mterceno** [comment]
Without page break, it works !
[without page break.pdf](https://github.com/jobsta/reportbro-lib/files/10537106/without.page.break.pdf)

**Comment by alhman** [comment]
Thank you for the detailed bug report. I was able to reproduce this issue with a much simpler report template. We'll let you know when we can provide a fix.

**Comment by mterceno** [comment]
Great! I glad to hear this. Thanks!
