### ISSUE TITLE
chinese support

### ISSUE THREAD

**Issue by wfrules** [jobsta/reportbro-lib#3]
when I tried the demo code(certificate.html) down from the web site(),I found the backend will raise exception when I preview the template with chinese character, and my reportServerUrl is "http://localhost:8000/reportbro/report/run", but if i changed it to "https://www.reportbro.com/report/run", it works! so i guess, i may download the wrong version of your code?  the down address is "https://www.reportbro.com/static/download/reportbro-lib.zip"
(Version 1.1.0, Jan 10, 2019)

**Comment by wfrules** [comment]
by the way ,the error message is "tornado.gen.BadYieldError: yielded unknown object '{"errors": []}'"...

**Comment by mariarauch** [comment]
You need to make the chinese font available both in the designer and in the lib (it's not included in the download package). Have a look at additional_fonts in the methods documentation: https://www.reportbro.com/docs/methods#reportbro-lib

**Comment by wfrules** [comment]
> You need to make the chinese font available both in the designer and in the lib (it's not included in the download package). Have a look at additional_fonts in the methods documentation: https://www.reportbro.com/docs/methods#reportbro-lib

I've already tried this way but it still not working.
my code is like this:


class MainHandler(tornado.web.RequestHandler):
    def initialize(self, db_connection):
        self.db_connection = db_connection
        # if using additional fonts then add to this list
        self.additional_fonts = [dict(value='Firefly', filename='E:/code/python/report/fonts/fireflysung.ttf')]
  ...........................................
       is there anything wrong?could you please give me some example?thks~

**Comment by 2524494878** [comment]
![image](https://user-images.githubusercontent.com/29651004/54736216-0d0c1380-4be5-11e9-91a9-bca374be5bad.png)
After my mining hole, I realized that I had to write firefly here to work

**Comment by mariarauch** [comment]
Documentation says that the configuration of additional fonts has to be done both in reportbro-designer and reportbro-lib. Values have to match.
