### ISSUE TITLE
Tipp excel dynamic formulas

### ISSUE THREAD

**Issue by GlauberF** [jobsta/reportbro-lib#31]
There is some study to be able to use similar expressions as in excel.
Example `=SUM(COL4)` , where here would be the sum of all column data(COL4) up to this point that has the expression.

another examples:

sum horizontally as.
`=SUM(COL1:COL4)`

`=DIV(...)`       division
`=SUB(...)`      subtraction
`=MULT(...)`   multiplication

It would generate even more dynamism to the library.

**Comment by alhman** [comment]
We have no plans to support excel formulas or the like. Lists do not have columns but named fields instead, therefor horizontal sum would not be possible anyway.

Maybe we will add custom functions at some point so you could create your own functions. In general data manipulation should be done on your side before the data is printed.
