### ISSUE TITLE
Conditional Formatting

### ISSUE THREAD

**Issue by alisufyanbaig-dev** [jobsta/reportbro-lib#32]
Hey there Thanks for the awesome library!

I just have a question that how can we apply multiple level of conditional formatting to table rows i.e. if value is
![Screenshot_1](https://user-images.githubusercontent.com/60003423/226119465-eb52056c-28f0-4c3b-8886-d46808d2b436.png)
 more than 10 color will be green, if value is less than 10 color will be red

**Comment by mariarauch** [comment]
With the latest release v3.3.0 we have added the feature to apply a ruleset of conditional styles. A usage guide will follow soon on the website. 
For your example use case this is the report:
https://gist.github.com/mariarauch/b4b648231a66567b04dfcb7e501fb408
