### ISSUE TITLE
SSRF on Image URL Import

### ISSUE THREAD

**Issue by aydinnyunus** [jobsta/reportbro-lib#39]
Hi,

I think there is a SSRF Vulnerability on Image URL Import functionality.

```
try:
                req = request.Request(image_url, headers=headers)
                self.image_data = BytesIO(request.urlopen(req).read())
            except Exception as ex:
                raise ReportBroError(
                    Error('errorMsgLoadingImageFailed', object_id=image_id, field='source', info=str(ex)))
```

If attacker gives internal URL it will return the response. I think the server needs to check if file is image or it can be very dangerous

**Comment by alhman** [comment]
When the image is actually used, it will be loaded with Pillow lib. If the data is invalid (or malicious) image loading will fail with an exception.

Images from external sources have to be explicitly enabled with `allow_external_image` setting when using the lib on your server.

**Comment by aydinnyunus** [comment]
Hi @alhman,

Thank you for your thorough explanation. I'm not very familiar with the library, but correct me if I'm mistaken. Even if the URL isn't an image, the request will still be sent, right? So, it could potentially be an internal URL, and an attacker could send a request to that internal URL to trigger the GET request. For instance, if there's an endpoint that deletes a user like http://victim/users/1/delete, it could delete user 1. Furthermore, even if it's explicitly enabled, I believe it still needs to be secure.

**Comment by alhman** [comment]
Not sure what you are suggesting. Your example would not do anything as an internal system would always have some kind of authentication.

You only know if the url returns a valid image after you received the data. There is no way to check the data in advance. If you cannot trust the users who create reports on your server you should not allow external images.

The only improvement I could think of would be some kind of url checking, either with a callback or regex etc. Then you could limit downloading images to specific urls.

**Comment by aydinnyunus** [comment]
If there is an authentication system as you said, this attack wouldn't be valid, but I mentioned it just as an example. It's not very feasible for authentication to be present in all services, and even if it were possible, it wouldn't be related to this library. I think the part concerning the library is sending this request to internal URLs. In Python, the is_private function can be used to prevent such situations. If the URL is private, the request may not be sent.
 

- https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv4Address.is_private

Also this is the same report as an impact which is CVSS score is 7.3/10

- https://github.com/MobSF/Mobile-Security-Framework-MobSF/security/advisories/GHSA-wfgj-wrgh-h3r3

**Comment by bmiklautz** [comment]
@aydinnyunus  [reportbro-lib](https://github.com/jobsta/reportbro-lib) is a merely library to generate PDF and XLSX reports from a report definition. If used as part of a web application it could theoretically be possible that the web application is vulnerable to a SSRF but therefore `allow_external_image` must **explicitly** be enabled (default is disabled) and other circumstances (like "user" editable reports) must apply as well. So I don't see this as a vulnerability of reportbro-lib itself.
