### ISSUE TITLE
Generate pdf failed error 500

### ISSUE THREAD

**Issue by devangwcg** [jobsta/reportbro-lib#9]
I am using reportbro-lib through Docker (Image : python:3.8.1-buster)
I'm sending 50 data with use of section which create 50 pages pdf working fine
But I'm getting following error for 20000 data
I have also tried with Python 3.6 and Python 3.7
And also checked no data are blank or null

```
ERROR:tornado.application:Uncaught exception PUT /rbro/report/save (172.19.0.6)
HTTPServerRequest(protocol='http', host='generate_pdf', method='PUT', uri='/rbro/report/save', version='HTTP/1.1', remote_ip='172.19.0.6')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
TypeError: object str can't be used in 'await' expression
ERROR:tornado.access:500 PUT /rbro/report/save (172.19.0.6) 612.54ms
```

**Comment by alhman** [comment]
You need to check which exception is thrown when generating the report. I assume its a RuntimeError with the message 'Too many pages (probably an endless loop)'. If your 20000 data rows will generate 20000 pages you will definitely reach the maximum page limit.

ReportBro has a limit of 10000 pages to avoid endless loops when generating a report. We can add a setting in the next version so you can configure the page limit when running reportbro on your server. Although I'm not sure if ReportBro is the right tool in your case as it is not optimized for huge data but has a focus on beautiful and easy layouts instead.

**Comment by alhman** [comment]
you can now set a custom page_limit (or no limit at all by setting page_limit=None) with the latest release 1.4.0
